### ISSUE TITLE
`version_repo` is not updated when Bazel version changes

### ISSUE THREAD

**Issue by meteorcloudy** [bazel-contrib/bazel_features#25]
When switching the Bazel version, the `bazel_features_version` repo generated by https://github.com/bazel-contrib/bazel_features/blob/1f1b95a6fcdc5bfcc67f7a845f3f5e8e89cc7d29/private/version_repo.bzl#L5-L5 won't be automatically updated, which could result wrong feature detection result.

**Comment by meteorcloudy** [comment]
I was switching between `6.4.0rc3` and `6.4.0`.

**Comment by fmeum** [comment]
We probably have to replace https://github.com/bazelbuild/bazel/blob/dc4f54f9c57a27b68ae0e8c0d21ad3cb68a3dc44/src/main/java/com/google/devtools/build/lib/packages/WorkspaceFactory.java#L363 with a regular struct field method that tracks whether a repository rule invoked it and then adds the return value to the marker file.

**Comment by fmeum** [comment]
This would be difficult, but I think there is a much simpler solution: https://github.com/bazel-contrib/bazel_features/pull/26

**Comment by meteorcloudy** [comment]
Yeah, the new solution is also better since it works for existing Bazel versions! Thank you!!
