### ISSUE TITLE
'@bazel_features_version' is not defined

### ISSUE THREAD

**Issue by LLlkaiwen** [bazel-contrib/bazel_features#27]
when I use bazel_features in bazel 5.
I meet the following error
external/bazel_features/private/util.bzl:1:6: Unable to find package for @bazel_features_version//:version.bzl: The repository '@bazel_features_version' could not be resolved: Repository '@bazel_features_version' is not defined.

**Comment by andrewkatson** [comment]
@LLlkaiwen how did you fix this?

**Comment by LoSealL** [comment]
I suppose bazel_features only supports to use with bzlmod (`--enable_bzlmod`), and not workable under legacy workspace

**Comment by fmeum** [comment]
It works with both, it's just far more difficult to get a sufficiently up-to-date version into your build with WORKSPACE, but that's not different from any other WORKSPACE dep.
