### ISSUE TITLE
Possible bug in `bazel_features` causing problem updating `rules_jvm_external` depndency

### ISSUE THREAD

**Issue by hb-man** [bazel-contrib/bazel_features#70]
Not sure in which of two projects the problem is
https://github.com/bazel-contrib/rules_jvm_external/issues/1256

Updating `rules_jvm_external` to version 6.4 causes `bazel_features` error

can be reproduced on this project/branch

https://github.com/JetBrains/hirschgarten/pull/68

full error message:
```
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @@bazel_features
This could either mean you have to add the '@@bazel_features' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
Computing main repo mapping:
ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
```

i tried fixing it by adding explicit dependency to bazel_features - but than i get another error:

```
ERROR: Failed to load Starlark extension '@@bazel_features_version//:version.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @@bazel_features_version
This could either mean you have to add the '@@bazel_features_version' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
```

Though, if I add bazel_features depndency explicit, but WORKSPACE-style - it starts to work. This might be a bug in bazel features so I'll file it there.

**Comment by fmeum** [comment]
I'm pretty sure that the bug is in the transitively updated rules_java, which is used by Bazel's workspace suffix but doesn't properly declare the dep on bazel_features here: https://github.com/bazelbuild/rules_java/blob/master/java/repositories.bzl

@hvadehra

**Comment by fmeum** [comment]
@daniel-b2c2 Yes, please do!

**Comment by fmeum** [comment]
See https://github.com/bazelbuild/rules_java/issues/225#issuecomment-2388494967, a closer look revealed that this is an issue with rules_sonatype.
